GET http://localhost:3001/infrastructures

###

PUT http://localhost:3001/infrastructures/:id

###

// ---------------- Pools queries ----------------------

GET http://localhost:3001/piscines

###

GET http://localhost:3001/bassins

###

GET http://localhost:3001/bassins/1


// ---------------- Sports center queries ----------------------
###

GET http://localhost:3001/centres

###

// ---------------- Patinoire queries ----------------------

GET http://localhost:3001/patinoires